### PR TITLE
Added and tested Asus USB-N66

### PR DESCRIPTION
**Pull request by nalt**

### CODE REVIEW

**Comment by kshchepanovskyi** [comment]
Have you tested this driver on x86_64 or on x86 machine?

**Comment by nalt** [comment]
Partial output from uname:
3.8.0-26-generic #38~precise2-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by kshchepanovskyi** [comment]
When I used this driver with Linksys AE3000 I saw a lot of error in dmesg log. Also, connection was not stable, and speed was much slower than should be (~ 30 mbit max with 100 mbit internet connection). 

I'll try to fix the errors that I saw in dmesg when I'll find some time.

**Comment by kshchepanovskyi** [comment]
P.S. compiler says that there are few places where a pointer (64 bit) casted to an integer (32 bit). Such casts are not acceptable on x86_64 arch.

**Comment by nalt** [comment]
Ok, but this is not related to the Asus device. You should create an issue for both problems and attach details.

**Comment by ashaffer** [comment]
@nalt Thanks, merging.

@schepanovsky I know it still has a lot of issues.  I too experience instability and slowness.  It definitely isn't completely fixed, its just usable at the moment.  I was hoping by now that RaLink would have created a real fix for us, but they have not done so yet.  Thanks for the tip about the pointer casts, i'll take a look at that.  Feel free to create a separate issue if you want to continue this discussion and trying to figure out the remaining issues together.

**Pull request merged**
